"""
Django settings for processing_platform project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY must be set")

DEBUG_RAW = os.environ.get("DEBUG")
if DEBUG_RAW is None:
    DEBUG = False
else:
    DEBUG = DEBUG_RAW.lower() in ("1", "true", "yes", "on")

_allowed_hosts_raw = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_vite",
    "rest_framework",
    "jobs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "processing_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "processing_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=60),
    }
elif os.environ.get("POSTGRES_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "postgres"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
            "HOST": os.environ["POSTGRES_HOST"],
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

DJANGO_VITE = {
  "default": {
    "dev_mode": True
  }
}

# Redis DB 0 — Celery message broker and result backend
def _redis_db_url(redis_url: str, db: int) -> str:
    parsed = urlparse(redis_url)
    base = redis_url
    if parsed.scheme and parsed.netloc:
        base = f"{parsed.scheme}://{parsed.netloc}"
        if parsed.query:
            return f"{base}/{db}?{parsed.query}"
        return f"{base}/{db}"
    return redis_url


REDIS_URL = os.environ.get("REDIS_URL")

CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL",
    os.environ.get(
        "CELERY_BROKER",
        _redis_db_url(REDIS_URL, 0) if REDIS_URL else "",
    ),
)
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND",
    os.environ.get("CELERY_BACKEND", CELERY_BROKER_URL),
)

# Task retry policy for background jobs (see jobs.tasks.process_job)
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_RETRY_MAX = int(os.environ.get("CELERY_TASK_RETRY_MAX", 3))
CELERY_TASK_RETRY_BACKOFF_MAX = int(
    os.environ.get("CELERY_TASK_RETRY_BACKOFF_MAX", 300)
)

# Redis DB 1 — Django cache (LLM-generated regex patterns keyed by prompt)
REDIS_CACHE_URL = os.environ.get(
    "REDIS_CACHE_URL",
    _redis_db_url(REDIS_URL, 1) if REDIS_URL else "",
)
REGEX_CACHE_TTL = int(os.environ.get("REGEX_CACHE_TTL", 60 * 60 * 24))  # 24 hours

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "KEY_PREFIX": "processingplatform",
        "TIMEOUT": REGEX_CACHE_TTL,
    }
}

# This is where uploaded files are stored
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

if not DEBUG:
    if not ALLOWED_HOSTS:
        raise RuntimeError("DJANGO_ALLOWED_HOSTS must be set when DEBUG=0")
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL must be set when DEBUG=0")
    if not CELERY_BROKER_URL or not CELERY_RESULT_BACKEND:
        raise RuntimeError(
            "CELERY_BROKER_URL/CELERY_RESULT_BACKEND (or REDIS_URL) must be set when DEBUG=0"
        )
    if not REDIS_CACHE_URL:
        raise RuntimeError("REDIS_CACHE_URL (or REDIS_URL) must be set when DEBUG=0")
    if not OPENAI_API_KEY:
        raise RuntimeError("OPENAI_API_KEY must be set when DEBUG=0")